name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure
        uses: actions/configure-pages@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Test remove install state
        run: rm -fv .yarn/install-state.gz
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build
      # - name: Install
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: install
      # - name: Build
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: build
      - name: Fix permissions
        run: |
          chmod -c -R +rX "dist/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
  deploy_ssh:
    environment:
      name: solaire
      url: https://sharparam.com
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
      - name: Extract artifact
        run: |
          mkdir -p dist
          tar -xvf artifact.tar -C dist
      - name: Upload
        run: |
          rsync \
            --verbose \
            --recursive \
            --links \
            --times \
            --specials \
            --rsh 'ssh -p ${{ secrets.SSH_PORT }}' \
            dist/ \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:sharparam.com/public_html/
